### ISSUE TITLE
Call to a member function label() on null

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/entity_plus#28] opened 2020-06-18 04:29 UTC
I upgraded a few modules on a dev site and started getting a maintenance screen with this error: `Call to a member function label() on null`.

I tracked it down to `entity_plus.theme.inc` where it's trying to set the `$entity` variable, but in at least one case that was apparently null. Does that make any sense to you @hosef? For the moment I'm just blocking the whole section in `template_preprocess_entity_plus` with a `if (!empty($variables['elements']['#entity'])) {`...

**Comment by laryn** [comment] 2020-06-30 13:11
This particular site seems to have an issue that I'll need to troubleshoot -- ~~I'm guessing this is related:
https://github.com/backdrop-contrib/paragraphs/issues/14~~ (Edit: not related)

That said, it's possible it's something particular with this site. Any ideas more than welcome however...

**Comment by laryn** [comment] 2020-07-24 21:10
[On this line](https://github.com/backdrop-contrib/entity_plus/blob/1.x/theme/entity_plus.theme.inc#L34):

```
  if (!empty($variables['elements']['#entity'])) {
    $entity = $variables['elements']['#entity'];
  }
  else {
    return;
  }

```

**Comment by jenlampton** [comment] 2021-09-12 00:47
I'm having the same problem after installing paragraphs, and attempting to override `paragraphs-item.tpl.php`, so I don't think it's specific to your site @laryn. 

I also noticed that for every paragraphs item, the paragraphs_item template is being applied twice. One time it only contains the class `entity_plus` (when it is stashed into the `#children` key of the renderable, with `#printed` is set to TRUE) so I wonder if entity_plus might be doing the rendering there?

See related: https://github.com/backdrop-contrib/paragraphs/issues/91

**Comment by jenlampton** [comment] 2021-09-12 23:06
The ParagraphsItem `view()` method calls `entity_get_controller($this->entityType())->view` which in this case, is `EntityPlusController()`. The `view()` method there contains this code comment: 
```
// If the entity type provides an implementation, use this instead the
// generic one.
// @see template_preprocess_entity()
```
I think maybe this is the problem. Not only has this documentation not been updated (I'm sure that was supposed to say `template_preprocess_entity_plus()` instead) but if it's attempting to add a theme hook suggestion that's not a derivative `entity_plus.tpl.php`, it's too late to do so here, because all the variables will have been already preprocessed as though they were intended for entity_plus, and not for the actual template being used.

I'm going to fiddle with this and see if changing the `#theme` here solves the problem. If not, I may be barking up the wrong tree :)

**Comment by jenlampton** [comment] 2021-09-12 23:23
Well, progress? If I change the theme hook here, the page seems to render correctly (with my template only applied once). But I don't know how to check the theme registry to see if a specific function is provided, so I ended up with this mess:

```
      // If the entity type provides its own themed output, use that instead.
        // @todo find out how to check the registry without calling this way.
      $themes = list_themes();
      $theme_registry = _theme_load_registry($themes['basis']); // Gah!
      if (array_key_exists($this->entityType, $theme_registry)) {
        $build['#theme'] = $this->entityType;
      }
```
...as well as some PHP errors. I'm going to sort through the errors and see if it sheds any other light.

**Comment by jenlampton** [comment] 2021-09-13 00:23
The PHP errors were helpful :) I think I found a fix for https://github.com/backdrop-contrib/paragraphs/issues/91.

> I'm having the same problem after installing paragraphs, and attempting to override `paragraphs-item.tpl.php`, so I don't think it's specific to your site @laryn. 

I suspect this issue may be specific to all sites with Paragraphs. Since implementing the fix above I haven't encountered this problem anymore. If someone else can confirm, maybe we can close this?

**Comment by laryn** [comment] 2021-09-13 14:07
Thank you @jenlampton -- the preliminary testing in the Paragraphs thread you linked looks promising enough that I'll close this one here. Thanks so much!

**Comment by laryn** [comment] 2021-10-13 16:47
Reopening as the fix in the Paragraphs queue breaks some preprocessing functionality. 

@hosef do you have any insight on how this might relate in Entity Plus's implementation where Paragraphs items are getting rendered twice? From @jenlampton in the Paragraphs thread:

> I think the problem was that we were telling the paragraph item to use the `paragraph_item` template as a theme wrapper, but it already renders using that template due to `entity_plus` changing the `theme_hook_suggestions` in `template_preprocess_entity_plus()`.

> I don't like how `entity_plus` is both providing theme output, and then switching the output source to use something else, but that seems to be as intended. In a perfect world all it would do is `render()` and allow whatever provided the thing to specify it's own output. I didn't try to fix it though, that seems hard :)

**Comment by laryn** [comment] 2021-12-04 04:53
@jenlampton mentioned the view method above. @herbdool  just mentioned that separately. Could this relate? I haven’t had time to dig but wanted to make the connection in a comment just in case:

https://github.com/backdrop-contrib/paragraphs/issues/106#issue-1070856192

**Comment by argiepiano** [comment] 2021-12-04 04:56
@laryn I'm looking into this issue, but I'm not clear how to reproduce the error. I installed paragraphs and it's working fine so far. Can you give me a clue on how to reproduce it?

**Comment by laryn** [comment] 2021-12-04 05:01
Add a template override for paragraphs-item.tpl.php in your theme, even if just copying the one from the paragraphs module.

**Comment by herbdool** [comment] 2021-12-04 05:32
@laryn maybe try `buildContent` method instead of `view`? Entity Plus would not add its own theme suggestions I think. Just spitballing.

**Comment by argiepiano** [comment] 2021-12-04 06:05
I think you are aware of this, but looking at the themed output, it looks like there is some theme nesting going on. Compare to D7's output below.

Currently Drupal 7 Paragraphs does not have a template_preprocess_paragraphs_item function, while Backdrop does. In Drupal template_preprocess_entity is called once per paragraph instance. Backdrop calls it twice, and calls template_preprocess_paragraphs_item as well. 

I don't know what all of this means, but I'll sleep over it. I'll keep looking into this tomorrow... 

BACKDROP'S OUTPUT 
<img width="456" alt="Screen Shot 2021-12-03 at 10 12 52 PM" src="https://user-images.githubusercontent.com/9938978/144699517-03705a29-c8e6-47bf-bb0f-2555eeb137e0.png">

DRUPAL'S OUTUT
<img width="388" alt="Screen Shot 2021-12-03 at 10 14 02 PM" src="https://user-images.githubusercontent.com/9938978/144699528-fc8cd759-8e1c-4c4f-955f-ae2212bbc9b4.png">

**Comment by argiepiano** [comment] 2021-12-04 15:32
@laryn , after moving the `paragraphs-item.tpl.php` file into the themes folder, I'm can't reproduce the error reported here. I left the tpl file intact and also verified that it's being called. Can you let me know if you have modified the tpl file (or any of the parent tpl files like `node.tpl.php` or `paragraphs-items.tpl.php`? For example, are you doing some custom printing of a sub-element of the $content array in any of those parent tpls?

HOWEVER, after quick inspection, I can confirm that the current version of Paragraph is double-printing (calling twice or three times per field) the   `paragraphs-item.tpl.php`,  invoked both by entity_plus and paragraphs, each time with a different $content. This double-calling causes the troubling nesting of divs with the same classes that you see in the images I posted above.

I discovered that @jenlampton had reported exactly this markup problem  in https://github.com/backdrop-contrib/paragraphs/issues/91#issuecomment-917349903 and she provided a PR that actually solves this. I will continue this conversation there.

In the meantime, if you could let me know about my tpl modifications questions I typed at the top of this comment I could test and see if I'm able to reproduce the error of this issue.

**Comment by argiepiano** [comment] 2021-12-04 19:08
@laryn I was able to reproduce the error reported here by enabling Modal Administration for Paragraphs, and by using a template file in the theme's folder rather than the one provided by the the module. So, that's progress.

I have a hunch that this (as well as https://github.com/backdrop-contrib/paragraphs/issues/91) is all caused by the double call of template file. I don't think this is a bug in Entity Plus, but rather an issue produced by that double call. 

The Paragraphs PR https://github.com/backdrop-contrib/paragraphs/pull/92 eliminated the double invocation of the template and produced a more sensible html markup output, BUT it interfered with the Modal Administration. I believe you re-added the #theme_wrappers line in Paragraphs [here](https://github.com/backdrop-contrib/paragraphs/blob/769e1db92419cfee145a80ee1e573c0f5a14cd00/paragraphs.field_formatter.inc#L128) to solve the Modal issue, according to the comments you inserted above that line.

I'm going to try to focus on making the Paragraph's Modal Administration work without re-adding that #theme_wrappers line. For starters, there is an issue with how classes are applied in `paragraphs-item.tpl.php` for which I'll create a PR over there. 

I'll keep you posted on any progress.

**Comment by argiepiano** [comment] 2021-12-05 15:50
This issue was the result of issues with Paragraphs that have been resolved. See https://github.com/backdrop-contrib/paragraphs/issues/110. Closing.

**Closed as completed by argiepiano** 2021-12-05 15:50 UTC
