### ISSUE TITLE
Fatal error - BD 1.20.3 update to 1.21.1 with PHP 7.0

### ISSUE THREAD

**Issue by albanycomputers** [backdrop-contrib/entity_plus#117] opened 2022-02-04 19:39 UTC
While updating a site from 1.20.3 to 1.21.1 I received a fatal error, I did a bit of experimenting and had to restore the site, finally got the site to update after changing the server to PHP 7.4.

Here is what I went through.

Fatal error: Declaration of EntityPlusControllerInterface::buildContent($entity, $view_mode = 'full', $langcode = NULL) must be compatible with EntityControllerInterface::buildContent(EntityInterface $entity, $view_mode = 'full', $langcode = NULL) in

Entity_plus is being used by paragraphs, classy paragraphs, Replicate Paragraphs and the other dependencies.

I deleted via ftp the entity_plus and uploaded the latest version of Entity Plus 1.x-1.0.14 and ran update.php still the same... deleted entity_plus folder again and now have a dependency error (obviously I know why)

Delete the paragraphs folders, again via ftp.. and site ran...

Deleted the other related folders to get the site limping along and tried to restore the backup I took with Backup & Migrate before I did the update.

I restored the site and checked for updates...

![image](https://user-images.githubusercontent.com/1705388/152592312-d4a50f7d-f80a-4ae1-b989-c4478b9ee8bb.png)

Before everything went toes up... I updated Core first...

Updated colorbox - ok

Checked again for updates and updated
entity_plus and Paragraphs

All seemed ok

Then updated Backdrop and I got this error again...

An AJAX HTTP error occurred. HTTP Result Code: 200 Debugging information follows. Path: https://new.donvalley.tv/core/update.php?op=selection&token=mKpTESuREWuy5_jTNJ37GA2sZxgF3sBS7Ays4phTllo&id=30&op=do_nojs&op=do StatusText: parsererror ResponseText: Fatal error: Declaration of EntityPlusControllerInterface::buildContent($entity, $view_mode = 'full', $langcode = NULL) must be compatible with EntityControllerInterface::buildContent(EntityInterface $entity, $view_mode = 'full', $langcode = NULL) in /home/sites/5a/9/90f6452333/public_html/subdomains/new/modules/entity_plus/includes/entity_plus.controller.inc on line 12

This is the same error as before. - The site was running php 7.0

Changed to php 7.4 - refreshed the page and the database updates completed 5 of 6 just sat there for a while.... so I refreshed the page and it did the same.

I then changed the url to the home page and it worked and re-ran update.php and all seems fine.

**Comment by albanycomputers** [comment] 2022-02-04 19:42
On Zulip, Attila Vasas suggested the following.

Try this hot fix in the modules/entity_plus/includes/entity_plus.controller.inc:

Remove , $content = array() from line 634
Before:
  public function buildContent($entity, $view_mode = 'full', $langcode = NULL, $content = array()) {
After:

  public function buildContent($entity, $view_mode = 'full', $langcode = NULL) {
Replace $content with array() in line 636
Before:
    $entity->content = $content;
After:
    $entity->content = array();

**Comment by argiepiano** [comment] 2022-02-05 04:26
I'm unable to replicate this issue with 7.4 and the latest versions of Entity Plus and Paragraphs (please note: b.org is still serving Pararaphs 1.0.0 - that's a bug. The latest version is 1.2.0-beta1). That has to be installed manually.

One clue -  core's `EntityControllerInterface:buildContent()` now uses type-hinting for the first argument, while `EntityPlusControllerInterface::buildContent()` does not.  It's strange that 7.4 has not been throwing this fatal error. @**Steve Moorhouse (Dr Albany) AKA Albany Computers**  - you mentioned that you were using 7.0 when the error was thrown. I'm wondering if 7.0 has a stricter way to check for matching type-hinting and throws this error. It looks like, when you updated to 7.4, this went away?

**Comment by argiepiano** [comment] 2022-02-05 04:44
Confirmed! I tried installing E+ and Paragraphs with PHP 7.1.33 (I do not have PHP 7.0 in my local). I was able to reproduce the error. The error goes away if you manually fix the type-hinting of buildContent (please notice that this is not the fix that Attila Vasas suggested above - his fix still produces the error).

I will provide a PR in a minute, which will be incorporated  in the next release. @laryn ,  this issue also needs to be fixed in Paragraphs

**Comment by argiepiano** [comment] 2022-02-05 04:54
PR #118 

@albanycomputers , it'd be great if you could check this fix in PHP 7.0

**Comment by argiepiano** [comment] 2022-02-05 05:02
Oh, one more thing @albanycomputers . Be sure to also apply the patch here to Paragraphs:
https://github.com/backdrop-contrib/paragraphs/pull/121

**Comment by argiepiano** [comment] 2022-02-05 05:02
Reopening while waiting for others to test this fix.

**Comment by albanycomputers** [comment] 2022-02-11 18:44
@argiepiano Sorry for only just getting back into this... it's been a busy/tiring week...

Could you clarify which of the above still needs testing... I don't want to waste time testing things that have been successful.

**Comment by argiepiano** [comment] 2022-02-11 19:07
@albanycomputers no need to test - but if you have a chance you would need to:

1. Download the dev version of Entity Plus, which already contains this PR and move it to your modules folder
2. Use PHP 7.0 or 7.1
3. Download the dev version of Paragraphs, which also contains a similar PR that fixed this issue and put it in the modules folder
4. Then just open the site. If you don't see the PHP fatal error anymore, then things are working as intended.

I've already tested this, so again, no need to do it again. Let me know if you see any issues.

**Comment by argiepiano** [comment] 2022-02-17 15:30
Closing, as this issue is now fixed.

**Closed as completed by argiepiano** 2022-02-17 15:30 UTC
